// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#    include "hardware/pio.h"
#endif

// --- //
// mux //
// --- //

#define mux_wrap_target 0
#define mux_wrap 11

static const uint16_t mux_program_instructions[] = {
    //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0x6004, //  1: out    pins, 4         side 0
    0xc100, //  2: irq    nowait 0        side 1
    0x21c1, //  3: wait   1 irq, 1        side 1
    0xc200, //  4: irq    nowait 0        side 2
    0x22c1, //  5: wait   1 irq, 1        side 2
    0xc400, //  6: irq    nowait 0        side 4
    0x24c1, //  7: wait   1 irq, 1        side 4
    0xc800, //  8: irq    nowait 0        side 8
    0x28c1, //  9: wait   1 irq, 1        side 8
    0xd000, // 10: irq    nowait 0        side 16
    0x30c1, // 11: wait   1 irq, 1        side 16
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mux_program = {
    .instructions = mux_program_instructions,
    .length       = 12,
    .origin       = -1,
};

static inline pio_sm_config mux_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mux_wrap_target, offset + mux_wrap);
    sm_config_set_sideset(&c, 5, false, false);
    return c;
}
#endif
