// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#    include "hardware/pio.h"
#endif

// --- //
// spi //
// --- //

#define spi_wrap_target 0
#define spi_wrap 9

static const uint16_t spi_program_instructions[] = {
    //     .wrap_target
    0x30c0, //  0: wait   1 irq, 0        side 1
    0xe028, //  1: set    x, 8            side 0
    0xb042, //  2: nop                    side 1
    0xa042, //  3: nop                    side 0
    0xb042, //  4: nop                    side 1
    0xa042, //  5: nop                    side 0
    0xb042, //  6: nop                    side 1
    0x4001, //  7: in     pins, 1         side 0
    0x1047, //  8: jmp    x--, 7          side 1
    0xd001, //  9: irq    nowait 1        side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spi_program = {
    .instructions = spi_program_instructions,
    .length       = 10,
    .origin       = -1,
};

static inline pio_sm_config spi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spi_wrap_target, offset + spi_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif